name: Manual trigger workflow

on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: git checkout develop
      - run: echo "SITE_URL=https://ienokoto.en-gine.dev" >> $GITHUB_ENV
      - run: echo "API_URL=https://ienokoto.jp" >> $GITHUB_ENV
      # インストールとビルド
      - name: Use Volta
        uses: volta-cli/action@v4
      - run: |
          yarn install --immutable && \
          yarn build --immutable
        env:
          RETRY_LIMIT: 5 # 再試行の最大回数を定義
      - name: Check if build was successful
        if: failure() # 前のステップが失敗した場合
        run: |
          retry_count=1
          while [ "$retry_count" -le "$RETRY_LIMIT" ] && [ ! -d "./dist" ]; do
            echo "Retrying build... ($retry_count/$RETRY_LIMIT)"
            yarn build
            ((retry_count++))
            sleep 5m  # ウェイト時間
          done
      # SSH 設定
      - name: SSH Deploy
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          name: ienokoto-staging.key
          known_hosts: ${{ secrets.STAGING_SSH_KNOWN_HOST }}
          config: |
            Host ienokoto-staging
              HostName ${{ secrets.STAGING_SSH_HOST_NAME }}
              User ${{ secrets.STAGING_SSH_USER }}
              IdentityFile ~/.ssh/ienokoto-staging.key
              Port 10022
              StrictHostKeyChecking no
      - name: rsync over SSH
        run: rsync -r ./static/ ienokoto-staging:/home/engine0606/en-gine.dev/public_html/ienokoto/static/
